# Generated by Django 4.2.7 on 2023-11-10 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APPs', '0002_wskills'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordsPic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='static/skills')),
            ],
        ),
    ]
